### ISSUE TITLE
The code sandbox example for Analytics is down.

### ISSUE THREAD

**Issue by Shaun-Regenbaum** [davedbase/solid-primitives#29]

**Comment by Shaun-Regenbaum** [comment]
Specfically this link: https://codesandbox.io/s/solid-create-analytics?file=/src/index.tsx

**Comment by thetarnav** [comment]
I think the analytics package isn't finished yet.

**Comment by Shaun-Regenbaum** [comment]
Yes I saw now, sorry about that! Maybe a quick comment about "stages" would help?

**Comment by thetarnav** [comment]
"Stages" are also a work in progress :D 
But I understand it that way: Packages marked as 0 or 1, aren't actually done yet, maybe they are published on npm, maybe not. 2 is finished and published, but is still pretty experimental, might change, be removed, etc. And the 3 up are the packages that have proven themselves, are stable, well tested, etc. At least in theory.
