### ISSUE TITLE
The once option in createVisibilityObserver primitive

### ISSUE THREAD

**Issue by AlidotSal** [davedbase/solid-primitives#35]
Changing the once option in createVisibilityObserver Doesn't. In the below code I want to log to console only the first time the element  gets visible on the page but results in logging every time the element is visible.
`const [isVisible] = createVisibilityObserver(() => elementRef, { once: true });

  createEffect(() => {
    if (isVisible()) {
      console.log('visible');
        };
      });`

**Comment by thetarnav** [comment]
Should be fixed in `@1.1.21`

**Comment by davedbase** [comment]
@AlidotSal @thetarnav apologies I didn't published properly. It's actually Version 1.2.0 that you should be installing with the relevant patch.
