### ISSUE TITLE
Cookie with `=` in value not handled

### ISSUE THREAD

**Issue by jceb** [davedbase/solid-primitives#4]
I observed in the code that cookies with multiple equal signs in the value aren't handled properly, e.g. CSRF tokens. The part of the value after the equal sign is discarded.

See https://github.com/davedbase/solid-primitives/blob/main/packages/cookie-store/src/index.ts#L89

**Comment by davedbase** [comment]
@jceb thanks so much for letting us know! @atk patched this and we published the change for you to use.

**Comment by jceb** [comment]
@davedbase @atk did you test the change? I have doubts that it actually works, because of the weird behavior when you run split with a second parameter.

This `'test=123=abc'.split(/(=)/,1)` gives me that `["test"]` which would break the code as it's accessing indexes 0 and 2. The latter doesn't exist anymore.

**Comment by davedbase** [comment]
Hey @jceb we're going to take another look at this. I personally hadn't tested it. I think @atk is going to patch it with a replace callback instead of split shortly.

**Comment by atk** [comment]
Sorry that it took so long. It's fixed now and the case is also unit-tested, so the next release of that package will surely work for you.

**Comment by davedbase** [comment]
@jceb @atk version 1.1.8 has bene published with the patch. =)
