### ISSUE TITLE
createMediaQuery initial state

### ISSUE THREAD

**Issue by otonashixav** [davedbase/solid-primitives#42]
Why does [createMediaQuery](https://github.com/davedbase/solid-primitives/blob/main/packages/media/src/index.ts) use onMount to update its signal instead of directly creating it with `mql.matches`? From my perspective this would return a signal reflecting the current state of the media query immediately instead of only after effects have run. Avoiding the effect also allows the primitive to be used outside reactive contexts by putting the cleanup call behind a getOwner check to avoid the dev warning e.g.

```ts
const createMediaQuery = (
  query: string,
  fallbackState: boolean = false,
  watchChange: boolean = true
): (() => boolean) => {
  let initialState = fallbackState;
  if (!isServer) {
    const mql = window.matchMedia(query);
    initialState = mql.matches;
    if (watchChange) {
      const onChange = () => setState(mql.matches);
      mql.addEventListener("change", onChange);
      if (getOwner()) {
        onCleanup(() => mql.removeEventListener("change", onChange));
      }
    }
  }
  const [state, setState] = createSignal(initialState);
  return state;
};
```

**Comment by davedbase** [comment]
This is a really good suggestion @otonashixav thanks! I've published the change in 1.1.11. I'll have to add tests to this now :-) thanks for reminding me to get that done.
