### ISSUE TITLE
Might want to make the solid `peerDependency` a bit more loose

### ISSUE THREAD

**Issue by amoutonbrady** [davedbase/solid-primitives#51]
When installing a package from `@solid-primitives/*` (`storage` for that instance) via `pnpm` (might be the case in other package manager), we get a sweet warning stating that the `peerDependencies` are not met:

```bash
pnpm add @solid-primitives/storage      
Packages: +1
+
Progress: resolved 585, reused 567, downloaded 1, added 1, done

dependencies:
+ @solid-primitives/storage 1.1.0

 WARN  Issues with peer dependencies found
.
└─┬ @solid-primitives/storage
  └── ✕ unmet peer solid-js@1.3.0: found 1.3.3
```

I believe this can be solved by loosing up a bit the requirements by doing something like that:

```
// package.json
{
  ...,
  "peerDependencies": {
    "solid-js": ">= 1.3.1"
  },
  ...
}
```

Feel free to tell me if that's already something being solved :)

**Comment by thetarnav** [comment]
Ahhh ok. The issue is probably that the solid-js version was set to `@1.3.0` instead of `@^1.3.0` at some point, and the packages were not republished after the fix.

**Comment by davedbase** [comment]
I believe we've mostly resolved this! If you notice a package where this hasn't been adjusted, please let me know.
