### ISSUE TITLE
Timer, and custom scheduler.

### ISSUE THREAD

**Issue by KpjComp** [davedbase/solid-primitives#60]
Not used solidjs yet, but it looks very interesting, and are just browsing code.

But in the solid primitives Timer is at level 3, and looking at the code you seem to allow supplying a custom Scheduler, and that's nice.  But if you do this, then how are you meant to handle the cleanup, or is this meant to be something you handle yourself.  If you do this clearInterval is also going to be run on a return value that's irrelevant. 

Wouldn't creating a custom scheduler be better if you supplied the skeduler and the clear.

```
{
  skeduler: () => any;
  clear(id:any)
}
```

**Comment by atk** [comment]
If we can spell it `scheduler` instead of `skeduler`, that'd be great.

**Comment by davedbase** [comment]
lmao @ atk

@KpjComp hoping you have a chance to dive into SolidJS. I designed this with the intention that a custom scheduler would ultimately return a wrapped setTimeout/setInterval so ultimately it would return an ID that clearInterval (which also works for timeouts) can cancel with. If you were designing a more custom function then you'll likely need a different implementation.

If you have suggestions on how to make this more flexible, I'd be all ears though!

**Comment by atk** [comment]
That was directed at me, not at you. I find your proposal really interesting, but there are a few things I want to consider:

* Composability/tree shaking - this should not increase the final bundle size of our users considerably
* Testability - both the schedulers need to be tested and there needs to be a controllable test scheduler
* Compatibility - we now make a point of allowing our primitives to run both on the client and the server

Thank you for your proposal.
