### ISSUE TITLE
Documentation problem

### ISSUE THREAD

**Issue by bramaudi** [davedbase/solid-primitives#7]
I think this originally came from the `@amoutonbrady/solid-i18n` repo and looks like this is need to be updated, here are the several problems why:

1. Incorrect Solid `render` import
```js
import { render } from "solid-js/dom"; // it should be form "solid-js/web"
```

2. Confusing package name

It says to install `@solid-primitives/i18n` but in code example still using `@amoutonbrady/solid-i18n` and it also missing the export **I18nProvider**

3. Inspiring library

I opened `@amoutonbrady/solid-i18n` and it was inspired by [rosetta](https://github.com/lukeed/rosetta) but here are from [dlv](https://github.com/developit/dlv/blob/master/index.js) so I thought it was a very different internationalization lib but they aren't.

**Comment by davedbase** [comment]
@bramaudi thanks for letting me know. Yeah I threw this together very quickly to support the solid-site translation project. Matter of fact even the types aren't completely right and needed to be adjusted. I'll have a look at sorting this all out shortly =)

**Comment by davedbase** [comment]
Thanks I adjusted it. I decided to leave the provider out because it's just a convenience wrapper. I changed the example to use the context hook. Thanks for letting us know about this!
